/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var e=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var u=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var g=(l,o)=>{for(var n in o)e(l,n,{get:o[n],enumerable:!0})},p=(l,o,n,s)=>{if(o&&typeof o=="object"||typeof o=="function")for(let d of u(o))!c.call(l,d)&&d!==n&&e(l,d,{get:()=>o[d],enumerable:!(s=t(o,d))||s.enumerable});return l};var r=l=>p(e({},"__esModule",{value:!0}),l);var m={};g(m,{default:()=>a});module.exports=r(m);var i=require("obsidian"),a=class extends i.Plugin{async onload(){console.log("Vault Chat plugin loaded")}onunload(){console.log("Vault Chat plugin unloaded")}};
